// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovjovvrtuyxjkjavcfws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92am92dnJ0dXl4amtqYXZjZndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NzY3NzUsImV4cCI6MjA2ODM1Mjc3NX0.Xuo1nRnBdVEuYbwyt8EY0ENLd9egMZ0ePrn_FDa8H68";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});